monolog:
    handlers:
        error_log:
            type: fingers_crossed
            action_level: warning
            handler: mv_error_db
            channels: mv_error_log
        mv_error_db:
            type: service
            id: mv_error_log.db_storage
            channels: mv_error_log